### ISSUE TITLE
跳出討論串行為(1.8)

### ISSUE THREAD

**Issue by ElvisChiang** [kodakjerec/bahamut-BBS-2#1]
現在討論串用手勢跳出很容易誤觸

- 使用選項關閉手勢
- 跳出討論串 show dialog 來確定

**Comment by kodakjerec** [comment]
下一版放進去了👌
![Screenshot_20240125_172054_BahaBBS](https://github.com/kodakjerec/bahamut-BBS-2/assets/13214439/16956004-29d1-477d-86aa-5aaa1d687aa3)

**Comment by kodakjerec** [comment]
1.8實現，關閉討論串
